# Generated by Django 4.1.1 on 2023-08-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0007_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
