# Generated by Django 4.1.1 on 2023-08-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0008_alter_subject_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='class1',
            new_name='classes',
        ),
    ]
