# Generated by Django 4.1.1 on 2023-08-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0013_staff_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_leave',
            old_name='data',
            new_name='date',
        ),
    ]
