# Generated by Django 4.1.1 on 2023-08-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0015_alter_staff_leave_updated_at_staff_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_feedback',
            name='status',
        ),
    ]
