# Generated by Django 4.1.1 on 2023-08-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0021_attendance_attendance_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='attendance_date',
        ),
        migrations.AlterField(
            model_name='attendance_report',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.attendance'),
        ),
    ]
